# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Docs"

on:  # yamllint disable-line rule:truthy
    pull_request:
        paths:
        - "**/*.md"
        - ".markdownlint-cli2.yaml"
        - "markdown-link-check.json"
    push:
        branches:
        - "master"
        paths:
        - "**/*.md"
        - ".markdownlint-cli2.yaml"
        - "markdown-link-check.json"
    workflow_call: null
# Add [skip ci] to commit message to skip CI.

permissions: {}  # yamllint disable-line rule:braces
#permissions: "read-all"
#permissions:
#    contents: "read" # Private repositories need read permission

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    markdown_format:
        name: "Markdown format"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 1
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3.5.3"
        -
            name: "Check Markdown formatting"
            uses: "DavidAnson/markdownlint-cli2-action@v11.0.0"
            with:
                globs: "**/*.md"

    markdown_link:
        name: "Markdown link"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 10
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3.5.3"
        -
            name: "Cache NPM"
            uses: "actions/cache@v3.3.1"
            with:
                path: "~/.npm"
                key: "${{ runner.os }}-npm-markdown-link-check"
        -
            name: "Install markdown-link-check"
            run: "npm install --global markdown-link-check"
        -
            name: "Check Markdown links"
            run: |
                git ls-files -z -- '*.md' \
                    | xargs -0 -- npm exec -- markdown-link-check -p -c markdown-link-check.json
